name: Build

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: "true"
      - name: Build the Docker image
        run: docker build . --file Dockerfile
