name: Publish

on:
  # Allow workflow to be run manually
  workflow_dispatch:
  # Trigger the workflow on publish
  release:
    types: [ published ]

jobs:
  build-test-publish:
    runs-on: ubuntu-22.04
    # Google authentication (google-github-actions/auth) requires these permissions
    # (by-pinja/cs-reusable-github-actions-workflows/.github/composite/gcp-artifactregistry-docker-build-and-upload)
    permissions:
        contents: read
        id-token: write
    timeout-minutes: 30

    steps:
      - name: Set Docker Tag (publish)
        shell: bash
        run: echo "DOCKER_TAG=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Print Docker Tag (debug)
        run: echo "${{ env.DOCKER_TAG }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: "true"
      
      - name: Build and upload to GAR
        if: github.actor != 'dependabot[bot]'
        uses: by-pinja/cs-reusable-github-actions-workflows/.github/composite/gcp-artifactregistry-docker-build-and-upload@0.17.0
        with:
          additionaltags: "${{ env.DOCKER_TAG }};"
          gcp_gar_repo: europe-north1-docker.pkg.dev/ptcs-docker-registry/pinja-common-docker
          gcp_service_account: pinja-common-gar-uploader@ptcs-docker-registry.iam.gserviceaccount.com
          gcp_workload_identity_provider_url: projects/460821833685/locations/global/workloadIdentityPools/pinja-common-artifactregistry/providers/github

